[colors.bright]
black = "0x198388"
blue = "0x277FFF"
cyan = "0x05A1F7"
green = "0x47D4B9"
magenta = "0x962AC3"
red = "0xEC0101"
white = "0xFFFFFF"
yellow = "0xFF8A18"

[colors.normal]
black = "0x1F2229"
blue = "0x367BF0"
cyan = "0x49AEE6"
green = "0x5EBDAB"
magenta = "0x9755B3"
red = "0xD41919"
white = "0xE6E6E6"
yellow = "0xFEA44C"

[colors.primary]
background = "0x000000"
foreground = "0xFFFFFF"

[font]
size = 11

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window.padding]
x = 12
y = 12

[window]
opacity = 0.75
